# Generated by Django 4.1.4 on 2022-12-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_craeted_date_todo_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
